repository: ZingLix/Go-Page
repository_url: https://github.com/ZingLix/Go-Page

timezone: Asia/Shanghai
lang: zh_CN

title: ZingLix Go
alias_en: ZingLix Go
alias_cn: ZingLix Go
description: 
keywords: Navi
url: https://go.zinglix.xyz
established_at: "2016-10-01T00:00+08:00"

author: ZingLix
author_url: https://zinglix.xyz
organization: ZingLix
organization_url: https://zinglix.xyz
contact: 

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor